### ISSUE TITLE
Breaking change introduced in version 1.11.4

### ISSUE THREAD

**Issue by ahx** [ory/hydra-client-ruby#2]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra-client-ruby/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra-client-ruby/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

A breaking change was made in the method signature of `OryHydraClient::AdminApi#accept_consent_request` in version 1.11.4. This caused a problem in one of our systems after updating _ory-hydra-client_ from version 1.10.6  to  version 1.11.4.

The breaking change was introduced in this [commit](https://github.com/ory/hydra-client-ruby/commit/13b56c2aed7236f45abe0dc46f6db547bc660bd2#diff-c77bb4b580790c44a060b8501fa3ec44e0954310e8b4de6331011c5310cf1365R68).

Whereas in version [1.10.6 the method should be called with a `:body`](https://github.com/ory/hydra-client-ruby/blob/v1.10.6/lib/ory-hydra-client/api/admin_api.rb#L65) option like this:

```ruby
admin_api.accept_consent_request(consent_challenge, body: accept_consent_request)
```

since version [1.11.4 is has to be called with a `:accept_consent_request` option](https://github.com/ory/hydra-client-ruby/blob/v1.11.4/lib/ory-hydra-client/api/admin_api.rb#L68) like that:

```ruby
admin_api.accept_consent_request(consent_challenge, accept_consent_request: accept_consent_request)
```
The same kind of breaking change was made for `OryHydraClient::AdminApi#accept_login_request`.

### Reproducing the bug

- Integrate Hydra using _ory-hydra-client_ for Ruby version 1.10.6 
- The system works ✨ 
- Update _ory-hydra-client_ to version >= 1.11.4
- The system fails with Hydra returning a 400, because unexpected parameters are sent. 💔

You cannot really catch this in a unit test without mocking the HTTP request, because the implementation does use an options Hash instead of named arguments or the like. So the requests goes all through to Hydra, which responds with 400.

### Version

`>= 1.11.4`

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

### Additional Context

While the new method signature makes total sense, a major version change should have indicated the breaking change.

**Comment by ahx** [comment]
I have not traced down the issue to the change in the generator, but I assume it has something to do with the updated version of the openapi-generator.

**Comment by gen1us2k** [comment]
You can find usage examples of admin API [here](https://github.com/ory/hydra-client-ruby/blob/master/docs/AdminApi.md#accept_consent_request)
```ruby
require 'time'
require 'ory-hydra-client'

api_instance = OryHydraClient::AdminApi.new
consent_challenge = 'consent_challenge_example' # String | 
opts = {
  accept_consent_request: OryHydraClient::AcceptConsentRequest.new # AcceptConsentRequest | 
}

begin
  # Accept a Consent Request
  result = api_instance.accept_consent_request(consent_challenge, opts)
  p result
rescue OryHydraClient::ApiError => e
  puts "Error when calling AdminApi->accept_consent_request: #{e}"
end
```

According to your example you need to pass accept_consent_request using dict 
```ruby
opts = {accept_consent_request: accept_consent_request}

admin_api.accept_consent_request(consent_challenge, opts)
```

**Comment by aeneasr** [comment]
Sorry about those breaking changes, we upgraded OpenAPI Generator to a newer version in order to fix some pesky bugs n the Ory Kratos generated SDK, and it appears to have introduced breaking changes in this SDK! Regarding actually resolving the issue, @gen1us2k has you covered :)

**Comment by ahx** [comment]
@gen1us2k, @aeneasr We were able to fix the issue after seeing our application fail pretty quickly. But thanks for the info.
Do you have a strategy how to avoid / detect these breaking changes in the future?

**Comment by aeneasr** [comment]
Probably tests? 😅 We have a Cypress test suite i. hydra you might be able to reuse
